### ISSUE TITLE
Is there a way to hide the menubar icon?

### ISSUE THREAD

**Issue by artemgordinskiy** [cliffom/appleHDAReset#1]
Thanks a lot for the app! Really helpful.

**Comment by cliffom** [comment]
Currently there is not but adding that would be trivial. However, once hidden, there would be no easy way to un-hide it without issuing a command to the terminal.

**Comment by artemgordinskiy** [comment]
I know a way to show the icon again by launching the app from the Finder, [like this](https://github.com/ArtemGordinsky/SpotiFree/blob/master/SpotiFree/MenuController.m). Would this be ok?

**Comment by cliffom** [comment]
I added the functionality to a [feature branch](https://github.com/cliffom/appleHDAReset/tree/feature/hideMenuBarIcon) and created a [pull request](https://github.com/cliffom/appleHDAReset/pull/2). Would you mind taking a look and providing me some feedback?

**Comment by artemgordinskiy** [comment]
Looks ok. I would only add some kind of a message pop-up telling how to get the icon back.
